-- K-Collector Admin — Schema completo
-- Ejecuta esto en el SQL Editor de Supabase antes de usar el mantenedor.
-- Es idempotente: se puede volver a ejecutar sin romper datos existentes.

-- ============================================================
-- 1) TIPOS ENUM
-- ============================================================

DO $$ BEGIN
  CREATE TYPE public.card_status AS ENUM ('pending', 'owned', 'for_trade', 'sold');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- 2) TABLAS BASE (sin dependencias externas)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.collection_types (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name        text        NOT NULL,
  short_name  text        NOT NULL UNIQUE,
  description text,
  icon        text,
  color       text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id               uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name     text,
  avatar_url       text,
  bias             text,
  bias_wrecker     text,
  collecting_since date,
  created_at       timestamptz DEFAULT now(),
  is_admin         boolean     NOT NULL DEFAULT false,
  biases           text[]      NOT NULL DEFAULT '{}'::text[]
);

-- Columna is_admin en caso de que user_profiles ya exista de antes
ALTER TABLE public.user_profiles
  ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;

-- ============================================================
-- 3) TABLAS CON DEPENDENCIAS DE PRIMER NIVEL
-- ============================================================

CREATE TABLE IF NOT EXISTS public.album_eras (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  collection_type_id bigint      NOT NULL REFERENCES public.collection_types (id),
  name               text        NOT NULL,
  short_name         text        NOT NULL,
  description        text,
  color              text,
  sort_order         integer     NOT NULL DEFAULT 0,
  is_active          boolean     NOT NULL DEFAULT true,
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.albums (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               text        NOT NULL,
  artist             text        NOT NULL DEFAULT 'BTS',
  short_name         text        NOT NULL,
  release_year       integer,
  release_date       date,
  color              text                 DEFAULT '#A855F7',
  cover_image_url    text,
  sort_order         integer              DEFAULT 0,
  is_active          boolean              DEFAULT true,
  created_at         timestamptz          DEFAULT now(),
  collection_type_id bigint               REFERENCES public.collection_types (id),
  era_id             bigint               REFERENCES public.album_eras (id)
);

-- Columnas nuevas en caso de que albums ya exista sin ellas
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS collection_type_id bigint REFERENCES public.collection_types (id);
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS era_id             bigint REFERENCES public.album_eras (id);
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS short_name         text;
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS release_date       date;

CREATE TABLE IF NOT EXISTS public.card_categories (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text    NOT NULL,
  short_name  text    NOT NULL,
  description text,
  color       text             DEFAULT '#E040A0',
  sort_order  integer          DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.album_versions (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id   integer NOT NULL REFERENCES public.albums (id) ON DELETE CASCADE,
  name       text    NOT NULL,
  short_name text,
  sort_order integer DEFAULT 0
);

-- ============================================================
-- 4) TABLAS CON DEPENDENCIAS DE SEGUNDO NIVEL
-- ============================================================

CREATE TABLE IF NOT EXISTS public.card_sets (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  album_id    bigint      NOT NULL REFERENCES public.albums (id),
  version_id  bigint               REFERENCES public.album_versions (id),
  category_id bigint               REFERENCES public.card_categories (id),
  name        text        NOT NULL,
  short_name  text        NOT NULL,
  description text,
  retailer    text,
  round       text,
  sort_order  integer     NOT NULL DEFAULT 0,
  is_active   boolean     NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cards (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id         integer     NOT NULL REFERENCES public.albums (id),
  version_id       integer              REFERENCES public.album_versions (id),
  category_id      integer     NOT NULL REFERENCES public.card_categories (id),
  member           text        NOT NULL,
  member_full_name text,
  member_emoji     text,
  retailer         text,
  card_name        text        NOT NULL,
  code             text        NOT NULL UNIQUE,
  image_path       text,
  rarity           text                 DEFAULT 'Common'
                               CHECK (rarity = ANY (ARRAY['Common','Rare','Ultra Rare','Limited'])),
  is_group         boolean              DEFAULT false,
  is_blurred       boolean              DEFAULT false,
  release_date     date,
  notes            text,
  created_at       timestamptz          DEFAULT now(),
  is_visible       boolean              DEFAULT false,
  card_set_id      bigint               REFERENCES public.card_sets (id)
);

-- Columna nueva en caso de que cards ya exista sin ella
ALTER TABLE public.cards ADD COLUMN IF NOT EXISTS card_set_id bigint REFERENCES public.card_sets (id);

-- Para la app móvil — seguimiento de colección por usuario
CREATE TABLE IF NOT EXISTS public.user_cards (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        uuid        NOT NULL REFERENCES auth.users (id),
  card_id        integer     NOT NULL REFERENCES public.cards (id),
  status         public.card_status  DEFAULT 'pending',
  quantity       integer              DEFAULT 1,
  acquired_date  timestamptz,
  trade_open     boolean              DEFAULT false,
  notes          text,
  created_at     timestamptz          DEFAULT now(),
  updated_at     timestamptz          DEFAULT now(),
  duplicate_count integer    NOT NULL DEFAULT 0
);

-- ============================================================
-- 5) ÍNDICES
-- ============================================================

CREATE UNIQUE INDEX IF NOT EXISTS cards_code_unique_idx ON public.cards (code);

-- ============================================================
-- 6) TRIGGER: crea perfil automáticamente al registrarse
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.user_profiles (id)
  VALUES (NEW.id)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================================
-- 7) MARCA TU USUARIO COMO ADMIN
-- Reemplaza el correo por tu email de login de Supabase Auth.
-- ============================================================

UPDATE public.user_profiles up
SET    is_admin = true
FROM   auth.users au
WHERE  up.id = au.id
  AND  au.email = 'TU_CORREO@EMAIL.COM';

-- ============================================================
-- 8) ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.user_profiles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.album_eras       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.albums           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.album_versions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_categories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_sets        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_cards       ENABLE ROW LEVEL SECURITY;

-- user_profiles: cada usuario solo ve su propio perfil
DROP POLICY IF EXISTS "users can read own profile" ON public.user_profiles;
CREATE POLICY "users can read own profile"
  ON public.user_profiles FOR SELECT TO authenticated
  USING (id = auth.uid());

DROP POLICY IF EXISTS "users can update own profile" ON public.user_profiles;
CREATE POLICY "users can update own profile"
  ON public.user_profiles FOR UPDATE TO authenticated
  USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Lectura pública de catálogo para usuarios autenticados
DROP POLICY IF EXISTS "catalog read for authenticated" ON public.albums;
CREATE POLICY "catalog read for authenticated"
  ON public.albums FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "collection_types read for authenticated" ON public.collection_types;
CREATE POLICY "collection_types read for authenticated"
  ON public.collection_types FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "album_eras read for authenticated" ON public.album_eras;
CREATE POLICY "album_eras read for authenticated"
  ON public.album_eras FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "versions read for authenticated" ON public.album_versions;
CREATE POLICY "versions read for authenticated"
  ON public.album_versions FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "categories read for authenticated" ON public.card_categories;
CREATE POLICY "categories read for authenticated"
  ON public.card_categories FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "card_sets read for authenticated" ON public.card_sets;
CREATE POLICY "card_sets read for authenticated"
  ON public.card_sets FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "cards read for authenticated" ON public.cards;
CREATE POLICY "cards read for authenticated"
  ON public.cards FOR SELECT TO authenticated USING (true);

-- user_cards: cada usuario gestiona las suyas
DROP POLICY IF EXISTS "users manage own cards" ON public.user_cards;
CREATE POLICY "users manage own cards"
  ON public.user_cards FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- Escritura de catálogo solo para admins
DROP POLICY IF EXISTS "admin write collection_types" ON public.collection_types;
CREATE POLICY "admin write collection_types"
  ON public.collection_types FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin write album_eras" ON public.album_eras;
CREATE POLICY "admin write album_eras"
  ON public.album_eras FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin write albums" ON public.albums;
CREATE POLICY "admin write albums"
  ON public.albums FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin write versions" ON public.album_versions;
CREATE POLICY "admin write versions"
  ON public.album_versions FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin write categories" ON public.card_categories;
CREATE POLICY "admin write categories"
  ON public.card_categories FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin write card_sets" ON public.card_sets;
CREATE POLICY "admin write card_sets"
  ON public.card_sets FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin write cards" ON public.cards;
CREATE POLICY "admin write cards"
  ON public.cards FOR ALL TO authenticated
  USING      (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

-- ============================================================
-- 9) STORAGE — bucket 'photocards'
-- ============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('photocards', 'photocards', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "admin upload photocards" ON storage.objects;
CREATE POLICY "admin upload photocards"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'photocards'
    AND EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin)
  );

DROP POLICY IF EXISTS "admin update photocards" ON storage.objects;
CREATE POLICY "admin update photocards"
  ON storage.objects FOR UPDATE TO authenticated
  USING      (bucket_id = 'photocards' AND EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin))
  WITH CHECK (bucket_id = 'photocards' AND EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "admin delete photocards" ON storage.objects;
CREATE POLICY "admin delete photocards"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'photocards' AND EXISTS (SELECT 1 FROM public.user_profiles p WHERE p.id = auth.uid() AND p.is_admin));

DROP POLICY IF EXISTS "public read photocards" ON storage.objects;
CREATE POLICY "public read photocards"
  ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'photocards');
